USE [master]
GO

/****** Object:  Database [TheFashionFactory]    Script Date: 8/6/2023 11:22:28 AM ******/
CREATE DATABASE [TheFashionFactory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TheFashionFactory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TheFashionFactory.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TheFashionFactory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\TheFashionFactory_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TheFashionFactory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TheFashionFactory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TheFashionFactory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TheFashionFactory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TheFashionFactory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TheFashionFactory] SET ARITHABORT OFF 
GO

ALTER DATABASE [TheFashionFactory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TheFashionFactory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TheFashionFactory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TheFashionFactory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TheFashionFactory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TheFashionFactory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TheFashionFactory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TheFashionFactory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TheFashionFactory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TheFashionFactory] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TheFashionFactory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TheFashionFactory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TheFashionFactory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TheFashionFactory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TheFashionFactory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TheFashionFactory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TheFashionFactory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TheFashionFactory] SET RECOVERY FULL 
GO

ALTER DATABASE [TheFashionFactory] SET  MULTI_USER 
GO

ALTER DATABASE [TheFashionFactory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TheFashionFactory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TheFashionFactory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TheFashionFactory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TheFashionFactory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TheFashionFactory] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TheFashionFactory] SET QUERY_STORE = ON
GO

ALTER DATABASE [TheFashionFactory] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TheFashionFactory] SET  READ_WRITE 
GO

